name: Compatibility builds

on:
  workflow_dispatch:
  schedule:
    - cron: '5 6 * * *'

jobs:
  compatibility:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        spring: ['', 'spring-next', 'spring-61-next']
        kotlin: ['', 'kotlin-next', 'kotlin-2-next']
        jackson: ['', 'jackson-next']

    name: Compatibility ${{ matrix.spring }} ${{ matrix.kotlin }} ${{ matrix.jackson }}

    steps:

    - name: Check out sources
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: List dependencies
      run: ./mvnw -D depedency:list -Dsort
    - name: Build
      run: ./mvnw -B verify -P${{ matrix.spring }},${{ matrix.kotlin }},${{ matrix.jackson }} --file pom.xml
